"""empty message

Revision ID: 30e83c8092c2
Revises: 49ed71fc69f0
Create Date: 2024-03-22 20:36:04.138373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e83c8092c2'
down_revision = '49ed71fc69f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('diameter',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('diameter',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
